---
- hosts: db
  become: yes
  gather_facts: no
  roles:
    - common
  tasks:
    - name: ensure packages are installed
      apt:
        name:
          - postgresql
          - libpq-dev
          - python3-psycopg2
          - acl
- hosts: db
  become: yes
  become_user: postgres
  gather_facts: no
  vars:
    ads_database: ads_microservice_production
    ads_user: ads
    auth_database: auth_microservice_production
    auth_user: auth
    password: '{{ postgresql_password }}'
  vars_files:
    - secrets.yml
  tasks:
    - name: ensure ads database is created
      postgresql_db:
        name: '{{ ads_database }}'
    - name: ensure user has access to ads database
      postgresql_user:
        db: '{{ ads_database }}'
        name: '{{ ads_user }}'
        password: '{{ password }}'
        priv: ALL
    - name: ensure user has no extra privileges
      postgresql_user:
        name: '{{ ads_user }}'
        role_attr_flags: NOSUPERUSER,NOCREATEDB
    - name: ensure no other user can access the ads database
      postgresql_privs:
        db: '{{ ads_database }}'
        role: PUBLIC
        type: database
        priv: ALL
        state: absent
    - name: ensure auth database is created
      postgresql_db:
        name: '{{ auth_database }}'
    - name: ensure user has access to auth database
      postgresql_user:
        db: '{{ auth_database }}'
        name: '{{ auth_user }}'
        password: '{{ password }}'
        priv: ALL
    - name: ensure user has no extra privileges
      postgresql_user:
        name: '{{ auth_user }}'
        role_attr_flags: NOSUPERUSER,NOCREATEDB
    - name: ensure no other user can access the auth database
      postgresql_privs:
        db: '{{ auth_database }}'
        role: PUBLIC
        type: database
        priv: ALL
        state: absent
