---
- hosts: app
  become: yes
  gather_facts: no
  vars:
    env_vars: |
      RABBITMQ_HOST=127.0.0.1
      RABBITMQ_USER=ads
      RABBITMQ_PASSWORD=password
      RACK_ENV=production
      ADS_DATABASE_URL=postgresql://ads:password@localhost/ads_microservice_production
      AUTH_DATABASE_URL=postgresql://auth:password@localhost/auth_microservice_production
  tasks:
    - name: ensure pip installed
      apt:
        name: python3-pip
    - name: ensure python dependencies installed
      pip:
        name: docker
    - name: ensure env file is uploaded
      copy:
        content: '{{ env_vars }}'
        dest: '/home/{{ ansible_user }}/.env'
